/*insert into p_city values (1,'Aceh Barat');
insert into p_city values (2,'Aceh Barat Daya');
insert into p_city values (3,'Aceh Besar');
insert into p_city values (4,'Aceh Jaya');
insert into p_city values (5,'Aceh Selatan');
insert into p_city values (6,'Aceh Singkil');
insert into p_city values (7,'Aceh Timiang');
insert into p_city values (8,'Aceh Tengah');
insert into p_city values (9,'Aceh Tenggara');
insert into p_city values (10,'Aceh Timur');
insert into p_city values (11,'Aceh Utara');
insert into p_city values (12,'Agam');
insert into p_city values (13,'Alor');
insert into p_city values (14,'Ambon');
insert into p_city values (15,'Asahan');
insert into p_city values (16,'Asmat');
insert into p_city values (17,'Badung');
insert into p_city values (18,'Balangan');
insert into p_city values (19,'Balikpapan');
insert into p_city values (20,'Banda Aceh');
insert into p_city values (21,'Bandar Lampung');
insert into p_city values (22,'Bandung');
insert into p_city values (23,'Bandung');
insert into p_city values (24,'Bandung Barat');
insert into p_city values (25,'Banggai');
insert into p_city values (26,'Banggai Kepulauan');
insert into p_city values (27,'Bangka');
insert into p_city values (28,'Bangka Barat');
insert into p_city values (29,'Bangka Selatan');
insert into p_city values (30,'Bangka Tengah');
insert into p_city values (31,'Bangkalan');
insert into p_city values (32,'Bangli');
insert into p_city values (33,'Banjar');
insert into p_city values (34,'Banjar');
insert into p_city values (35,'Banjarbaru');
insert into p_city values (36,'Banjarmasin');
insert into p_city values (37,'Banjarnegara');
insert into p_city values (38,'Bantaeng');
insert into p_city values (39,'Bantul');
insert into p_city values (40,'Banyuasin');
insert into p_city values (41,'Banyumas');
insert into p_city values (42,'Banyuwangi');
insert into p_city values (43,'Barito Kuala');
insert into p_city values (44,'Barito Selatan');
insert into p_city values (45,'Barito Timur');
insert into p_city values (46,'Barito Utara');
insert into p_city values (47,'Barru');
insert into p_city values (48,'Batam');
insert into p_city values (49,'Batang');
insert into p_city values (50,'Batang Hari');
insert into p_city values (51,'Batu');
insert into p_city values (52,'Batu Bara');
insert into p_city values (53,'Bau-Bau');
insert into p_city values (54,'Bekasi');
insert into p_city values (55,'Bekasi');
insert into p_city values (56,'Belitung');
insert into p_city values (57,'Belitung');
insert into p_city values (58,'Belu');
insert into p_city values (59,'Bener Meriah');
insert into p_city values (60,'Bengkalis');
insert into p_city values (61,'Bengkayang');
insert into p_city values (62,'Bengkulu');
insert into p_city values (63,'Bengkulu Selatan');
insert into p_city values (64,'Bengkulu Tengah');
insert into p_city values (65,'Bengkulu Utara');
insert into p_city values (66,'Berau');
insert into p_city values (67,'Biak Numfor');
insert into p_city values (68,'Bima');
insert into p_city values (69,'Bima');
insert into p_city values (70,'Binjai');
insert into p_city values (71,'Bintan');
insert into p_city values (72,'Bireuen');
insert into p_city values (73,'Bitung');
insert into p_city values (74,'Blitar');
insert into p_city values (75,'Blitar');
insert into p_city values (76,'Blora');
insert into p_city values (77,'Boalemo');
insert into p_city values (78,'Bogor');
insert into p_city values (79,'Bogor');
insert into p_city values (80,'Bojonegoro');
insert into p_city values (81,'Bolaang Mongondow (Bolmong)');
insert into p_city values (82,'Bolaang Mongondow Selatan');
insert into p_city values (83,'Bolaang Mongondow Timur');
insert into p_city values (84,'Bolaang Mongondow Utara');
insert into p_city values (85,'Bombana');
insert into p_city values (86,'Bondowoso');
insert into p_city values (87,'Bone');
insert into p_city values (88,'Bone Bolango');
insert into p_city values (89,'Bontang');
insert into p_city values (90,'Boven Digoel');
insert into p_city values (91,'Boyolali');
insert into p_city values (92,'Brebes');
insert into p_city values (93,'Bukittinggi');
insert into p_city values (94,'Buleleng');
insert into p_city values (95,'Bulukumba');
insert into p_city values (96,'Bulungan (Bulongan)');
insert into p_city values (97,'Bungo');
insert into p_city values (98,'Buol');
insert into p_city values (99,'Buru');
insert into p_city values (100,'Buru Selatan');
insert into p_city values (101,'Buton');
insert into p_city values (102,'Buton Utara');
insert into p_city values (103,'Ciamis');
insert into p_city values (104,'Cianjur');
insert into p_city values (105,'Cilacap');
insert into p_city values (106,'Cilegon');
insert into p_city values (107,'Cimahi');
insert into p_city values (108,'Cirebon');
insert into p_city values (109,'Cirebon');
insert into p_city values (110,'Dairi');
insert into p_city values (111,'Deiyai (Deliyai)');
insert into p_city values (112,'Deli Serdang');
insert into p_city values (113,'Demak');
insert into p_city values (114,'Denpasar');
insert into p_city values (115,'Depok');
insert into p_city values (116,'Dharmasraya');
insert into p_city values (117,'Dogiyai');
insert into p_city values (118,'Dompu');
insert into p_city values (119,'Donggala');
insert into p_city values (120,'Dumai');
insert into p_city values (121,'Empat Lawang');
insert into p_city values (122,'Ende');
insert into p_city values (123,'Enrekang');
insert into p_city values (124,'Fakfak');
insert into p_city values (125,'Flores Timur');
insert into p_city values (126,'Garut');
insert into p_city values (127,'Gayo Lues');
insert into p_city values (128,'Gianyar');
insert into p_city values (129,'Gorontalo');
insert into p_city values (130,'Gorontalo');
insert into p_city values (131,'Gorontalo Utara');
insert into p_city values (132,'Gowa');
insert into p_city values (133,'Gresik');
insert into p_city values (134,'Grobogan');
insert into p_city values (135,'Gunung Kidul');
insert into p_city values (136,'Gunung Mas');
insert into p_city values (137,'Gunungsitoli');
insert into p_city values (138,'Halmahera Barat');
insert into p_city values (139,'Halmahera Selatan');
insert into p_city values (140,'Halmahera Tengah');
insert into p_city values (141,'Halmahera Timur');
insert into p_city values (142,'Halmahera Utara');
insert into p_city values (143,'Hulu Sungai Selatan');
insert into p_city values (144,'Hulu Sungai Tengah');
insert into p_city values (145,'Hulu Sungai Utara');
insert into p_city values (146,'Humbang Hasundutan');
insert into p_city values (147,'Indragiri Hilir');
insert into p_city values (148,'Indragiri Hilir');
insert into p_city values (149,'Indramayu');
insert into p_city values (150,'Intan Jaya');
insert into p_city values (151,'Jakarta Barat');
insert into p_city values (152,'Jakarta Pusat');
insert into p_city values (153,'Jakarta Selatan');
insert into p_city values (154,'Jakarta Timur');
insert into p_city values (155,'Jakarta Utara');
insert into p_city values (156,'Jambi');
insert into p_city values (157,'Jayapura');
insert into p_city values (158,'Jayapura');
insert into p_city values (159,'Jayawijaya');
insert into p_city values (160,'Jember');
insert into p_city values (161,'Jembrana');
insert into p_city values (162,'Jeneponto');
insert into p_city values (163,'Jepara');
insert into p_city values (164,'Jombang');
insert into p_city values (165,'Kaimana');
insert into p_city values (166,'Kampar');
insert into p_city values (167,'Kapuas');
insert into p_city values (168,'Kapuas Hulu');
insert into p_city values (169,'Karanganyar');
insert into p_city values (170,'Karangasem');
insert into p_city values (171,'Karawang');
insert into p_city values (172,'Karimun');
insert into p_city values (173,'Karo');
insert into p_city values (174,'Katingan');
insert into p_city values (175,'Kaur');
insert into p_city values (176,'Kayong Utara');
insert into p_city values (177,'Kebumen');
insert into p_city values (178,'Kediri');
insert into p_city values (179,'Kediri');
insert into p_city values (180,'Keerom');
insert into p_city values (181,'Kendal');
insert into p_city values (182,'Kendari');
insert into p_city values (183,'Kepahiang');
insert into p_city values (184,'Kepulauan Anambas');
insert into p_city values (185,'Kepulauan Aru');
insert into p_city values (186,'Kepulauan Mentawai');
insert into p_city values (187,'Kepulauan Meranti');
insert into p_city values (188,'Kepulauan Sangihe');
insert into p_city values (189,'Kepulauan Seribu');
insert into p_city values (190,'Kepulauan Siau Tagulandang Biaro (Sitaro)');
insert into p_city values (191,'Kepulauan Sula');
insert into p_city values (192,'Kepulauan Talaud');
insert into p_city values (193,'Kepulauan Yapen (Yapen Waropen)');
insert into p_city values (194,'Kerinci');
insert into p_city values (195,'Ketapang');
insert into p_city values (196,'Klaten');
insert into p_city values (197,'Klungkung');
insert into p_city values (198,'Kolaka');
insert into p_city values (199,'Kolaka Utara');
insert into p_city values (200,'Konawe');
insert into p_city values (201,'Konawe Selatan');
insert into p_city values (202,'Konawe Utara');
insert into p_city values (203,'Kotabaru');
insert into p_city values (204,'Kotamobagu');
insert into p_city values (205,'Kotawaringin Barat');
insert into p_city values (206,'Kotawaringin Timur');
insert into p_city values (207,'Kuantan Singingi');
insert into p_city values (208,'Kubu Raya');
insert into p_city values (209,'Kudus');
insert into p_city values (210,'Kulon Progo');
insert into p_city values (211,'Kuningan');
insert into p_city values (212,'Kupang');
insert into p_city values (213,'Kupang');
insert into p_city values (214,'Kutai Barat');
insert into p_city values (215,'Kutai Kartanegara');
insert into p_city values (216,'Kutai Timur');
insert into p_city values (217,'Labuhan Batu');
insert into p_city values (218,'Labuhan Batu Selatan');
insert into p_city values (219,'Labuhan Batu Utara');
insert into p_city values (220,'Lahat');
insert into p_city values (221,'Lamandau');
insert into p_city values (222,'Lamongan');
insert into p_city values (223,'Lampung Barat');
insert into p_city values (224,'Lampung Selatan');
insert into p_city values (225,'Lampung Tengah');
insert into p_city values (226,'Lampung Timur');
insert into p_city values (227,'Lampung Utara');
insert into p_city values (228,'Landak');
insert into p_city values (229,'Langkat');
insert into p_city values (230,'Langsa');
insert into p_city values (231,'Lanny Jaya');
insert into p_city values (232,'Lebak');
insert into p_city values (233,'Lebong');
insert into p_city values (234,'Lembata');
insert into p_city values (235,'Lhokseumawe');
insert into p_city values (236,'Lima Puluh Koto / Kota');
insert into p_city values (237,'Lingga');
insert into p_city values (238,'Lombok Barat');
insert into p_city values (239,'Lombok Tengah');
insert into p_city values (240,'Lombok Timur');
insert into p_city values (241,'Lombok Utara');
insert into p_city values (242,'Lubuk Linggau');
insert into p_city values (243,'Lumajang');
insert into p_city values (244,'Luwu');
insert into p_city values (245,'Luwu Timur');
insert into p_city values (246,'Luwu Utara');
insert into p_city values (247,'Madiun');
insert into p_city values (248,'Madiun');
insert into p_city values (249,'Magelang');
insert into p_city values (250,'Magelang');
insert into p_city values (251,'Magetan');
insert into p_city values (252,'Majalengka');
insert into p_city values (253,'Majene');
insert into p_city values (254,'Makassar');
insert into p_city values (255,'Malang');
insert into p_city values (256,'Malang');
insert into p_city values (257,'Malinau');
insert into p_city values (258,'Maluku Barat Daya');
insert into p_city values (259,'Maluku Tengah');
insert into p_city values (260,'Maluku Tenggara');
insert into p_city values (261,'Maluku Tenggara Barat');
insert into p_city values (262,'Mamasa');
insert into p_city values (263,'Mamberamo Raya');
insert into p_city values (264,'Mamberamo Tengah');
insert into p_city values (265,'Mamuju');
insert into p_city values (266,'Mamuju Utara');
insert into p_city values (267,'Manado');
insert into p_city values (268,'Mandailing Natal');
insert into p_city values (269,'Manggarai');
insert into p_city values (270,'Manggarai Barat');
insert into p_city values (271,'Manggarai Timur');
insert into p_city values (272,'Manokwari');
insert into p_city values (273,'Manokwari Selatan');
insert into p_city values (274,'Mappi');
insert into p_city values (275,'Maros');
insert into p_city values (276,'Mataram');
insert into p_city values (277,'Maybrat');
insert into p_city values (278,'Medan');
insert into p_city values (279,'Melawi');
insert into p_city values (280,'Merangin');
insert into p_city values (281,'Merauke');
insert into p_city values (282,'Mesuji');
insert into p_city values (283,'Metro');
insert into p_city values (284,'Mimika');
insert into p_city values (285,'Minahasa');
insert into p_city values (286,'Minahasa Selatan');
insert into p_city values (287,'Minahasa Tenggara');
insert into p_city values (288,'Minahasa Utara');
insert into p_city values (289,'Mojokerto');
insert into p_city values (290,'Mojokerto');
insert into p_city values (291,'Morowali');
insert into p_city values (292,'Muara Enim');
insert into p_city values (293,'Muaro Jambi');
insert into p_city values (294,'Muko Muko');
insert into p_city values (295,'Muna');
insert into p_city values (296,'Murung Raya');
insert into p_city values (297,'Musi Banyuasin');
insert into p_city values (298,'Musi Rawas');
insert into p_city values (299,'Nabire');
insert into p_city values (300,'Nagan Raya');
insert into p_city values (301,'Nagekeo');
insert into p_city values (302,'Natuna');
insert into p_city values (303,'Nduga');
insert into p_city values (304,'Ngada');
insert into p_city values (305,'Nganjuk');
insert into p_city values (306,'Ngawi');
insert into p_city values (307,'Nias');
insert into p_city values (308,'Nias Barat');
insert into p_city values (309,'Nias Selatan');
insert into p_city values (310,'Nias Utara');
insert into p_city values (311,'Nunukan');
insert into p_city values (312,'Ogan Ilir');
insert into p_city values (313,'Organ Komering Ilir');
insert into p_city values (314,'Ogan Komering Ulu');
insert into p_city values (315,'Ogan Komering Ulu Selatan');
insert into p_city values (316,'Ogan Komering Ulu Timur');
insert into p_city values (317,'Pacitan');
insert into p_city values (318,'Padang');
insert into p_city values (319,'Padang Lawas');
insert into p_city values (320,'Padang Lawas Utara');
insert into p_city values (321,'Padang Panjang');
insert into p_city values (322,'Padang Pariaman');
insert into p_city values (323,'Padang Sidempuan');
insert into p_city values (324,'Pagar Alam');
insert into p_city values (325,'Pakpak Bharat');
insert into p_city values (326,'Palangka Raya');
insert into p_city values (327,'Palembang');
insert into p_city values (328,'Polopo');
insert into p_city values (329,'Palu');
insert into p_city values (330,'Pamekasan');
insert into p_city values (331,'Pandeglang');
insert into p_city values (332,'Pangandaran');
insert into p_city values (333,'Pangkajene Kepulauan');
insert into p_city values (334,'Pangkal Pinang');
insert into p_city values (335,'Paniai');
insert into p_city values (336,'Parepare');
insert into p_city values (337,'Pariaman');
insert into p_city values (338,'Parigi Moutong');
insert into p_city values (339,'Pasaman');
insert into p_city values (340,'Pasaman Barat');
insert into p_city values (341,'Paser');
insert into p_city values (342,'Pasuruan');
insert into p_city values (343,'Pasuruan');
insert into p_city values (344,'Pati');
insert into p_city values (345,'Payakumbuh');
insert into p_city values (346,'Pegunungan Arfak');
insert into p_city values (347,'Pegunungan Bintang');
insert into p_city values (348,'Pekalongan');
insert into p_city values (349,'Pekalongan');
insert into p_city values (350,'Pekanbaru');
insert into p_city values (351,'Pelalawan');
insert into p_city values (352,'Pemalang');
insert into p_city values (353,'Pematang Siantar');
insert into p_city values (354,'Penajam Paser Utara');
insert into p_city values (355,'Pesawaran');
insert into p_city values (356,'Pesisir Barat');
insert into p_city values (357,'Pesisir Selatang');
insert into p_city values (358,'Pidie');
insert into p_city values (359,'Pidie Jaya');
insert into p_city values (360,'Pinrang');
insert into p_city values (361,'Pohuwato');
insert into p_city values (362,'Polewali Mandar');
insert into p_city values (363,'Ponorogo');
insert into p_city values (364,'Pontianak');
insert into p_city values (365,'Pontianak');
insert into p_city values (366,'Poso');
insert into p_city values (367,'Prabumulih');
insert into p_city values (368,'Pringsewu');
insert into p_city values (369,'Probolinggo');
insert into p_city values (370,'Probolinggo');
insert into p_city values (371,'Pulang Pisau');
insert into p_city values (372,'Pulau Morotai');
insert into p_city values (373,'Puncak');
insert into p_city values (374,'Puncak Jaya');
insert into p_city values (375,'Purbalingga');
insert into p_city values (376,'Purwakarta');
insert into p_city values (377,'Purworejo');
insert into p_city values (378,'Raja Ampat');
insert into p_city values (379,'Rejang Lebong');
insert into p_city values (380,'Rembang');
insert into p_city values (381,'Rokan Hilir');
insert into p_city values (382,'Rokan Hulu');
insert into p_city values (383,'Rote Ndao');
insert into p_city values (384,'Sabang');
insert into p_city values (385,'Sabu Raijua');
insert into p_city values (386,'Salatiga');
insert into p_city values (387,'Samarinda');
insert into p_city values (388,'Sambas');
insert into p_city values (389,'Samosir');
insert into p_city values (390,'Sampang');
insert into p_city values (391,'Sanggau');
insert into p_city values (392,'Sarmi');
insert into p_city values (393,'Sarolangun');
insert into p_city values (394,'Sawah Lunto');
insert into p_city values (395,'Sekadau');
insert into p_city values (396,'Selayar (Kepulauan Selayar)');
insert into p_city values (397,'Seluma');
insert into p_city values (398,'Semarang');
insert into p_city values (399,'Semarang');
insert into p_city values (400,'Seram Bagian Barat');
insert into p_city values (401,'Seram Bagian Timur');
insert into p_city values (402,'Serang');
insert into p_city values (403,'Serang');
insert into p_city values (404,'Serdang Bedagai');
insert into p_city values (405,'Seruyan');
insert into p_city values (406,'Siak');
insert into p_city values (407,'Sibolga');
insert into p_city values (408,'Sidenreng Rappang / Rapang');
insert into p_city values (409,'Sidoarjo');
insert into p_city values (410,'Sigi');
insert into p_city values (411,'Sijunjung (Sawah Lunto Sijunjung)');
insert into p_city values (412,'Sikka');
insert into p_city values (413,'Simalungun');
insert into p_city values (414,'Simeulue');
insert into p_city values (415,'Singkawang');
insert into p_city values (416,'Sinjai');
insert into p_city values (417,'Sintang');
insert into p_city values (418,'Situbondo');
insert into p_city values (419,'Sleman');
insert into p_city values (420,'Solok');
insert into p_city values (421,'Solok');
insert into p_city values (422,'Solok Selatan');
insert into p_city values (423,'Soppeng');
insert into p_city values (424,'Sorong');
insert into p_city values (425,'Sorong');
insert into p_city values (426,'Sorong Selatan');
insert into p_city values (427,'Sragen');
insert into p_city values (428,'Subang');
insert into p_city values (429,'Subulussalam');
insert into p_city values (430,'Sukabumi');
insert into p_city values (431,'Sukabumi');
insert into p_city values (432,'Sukamara');
insert into p_city values (433,'Kuloharjo');
insert into p_city values (434,'Sumba Barat');
insert into p_city values (435,'Sumba Barat Daya');
insert into p_city values (436,'Sumba Tengah');
insert into p_city values (437,'Sumba Timur');
insert into p_city values (438,'Sumbawa');
insert into p_city values (439,'Sumbawa Barat');
insert into p_city values (440,'Sumedang');
insert into p_city values (441,'Sumenep');
insert into p_city values (442,'Sungaipenuh');
insert into p_city values (443,'Supiori');
insert into p_city values (444,'Surabaya');
insert into p_city values (445,'Surakarta (Solo)');
insert into p_city values (446,'Tabalong');
insert into p_city values (447,'Tabanan');
insert into p_city values (448,'Takalar');
insert into p_city values (449,'Tambrauw');
insert into p_city values (450,'Tana Tidung');
insert into p_city values (451,'Tana Toraja');
insert into p_city values (452,'Tanah Bumbu');
insert into p_city values (453,'Tanah Datar');
insert into p_city values (454,'Tanah Laut');
insert into p_city values (455,'Tangerang');
insert into p_city values (456,'Tangerang');
insert into p_city values (457,'Tangerang Selatan');
insert into p_city values (458,'Tanggamus');
insert into p_city values (459,'Tanjung Balai');
insert into p_city values (460,'Tanjung Jabung Barat');
insert into p_city values (461,'Tanjung Jabung Timur');
insert into p_city values (462,'Tanjung Pinang');
insert into p_city values (463,'Tapanuli Selatan');
insert into p_city values (464,'Tapanuli Tengah');
insert into p_city values (465,'Tapanuli Utara');
insert into p_city values (466,'Tapin');
insert into p_city values (467,'Tarakan');
insert into p_city values (468,'Tasikmalaya');
insert into p_city values (469,'Tasikmalaya');
insert into p_city values (470,'Tebing Tinggi');
insert into p_city values (471,'Tebo');
insert into p_city values (472,'Tegal');
insert into p_city values (473,'Tegal');
insert into p_city values (474,'Teluk Bintuni');
insert into p_city values (475,'Teluk Wondama');
insert into p_city values (476,'Temanggung');
insert into p_city values (477,'Ternate');
insert into p_city values (478,'Tidore Kepulauan');
insert into p_city values (479,'Timor Tengah Selatan');
insert into p_city values (480,'Timor Tengah Utara');
insert into p_city values (481,'Toba Samosir');
insert into p_city values (482,'Tojo Una-Una');
insert into p_city values (483,'Toli-Toli');
insert into p_city values (484,'Tolikara');
insert into p_city values (485,'Tomohon');
insert into p_city values (486,'Toraja Utara');
insert into p_city values (487,'Trenggalek');
insert into p_city values (488,'Tual');
insert into p_city values (489,'Tuban');
insert into p_city values (490,'Tulang Bawang');
insert into p_city values (491,'Tulang Bawang Barat');
insert into p_city values (492,'Tulungagung');
insert into p_city values (493,'Wajo');
insert into p_city values (494,'Wakatobi');
insert into p_city values (495,'Waropen');
insert into p_city values (496,'Way Kanan');
insert into p_city values (497,'Wonogiri');
insert into p_city values (498,'Wonosobo');
insert into p_city values (499,'Yahukimo');
insert into p_city values (500,'Yalimo');
insert into p_city values (501,'Yogyakarta');*/


select max(a.City_Id)as MaxCityID,a.City_Name from p_city a 
group by a.City_Name
having count (*)> 2

 SELECT MAX(t.City_Id) AS maxid,t.City_Name
  FROM p_city t
  JOIN p_city AS duplicates
  USING (t.City_Name)
  GROUP BY t.City_Name
  HAVING COUNT(*) > 1
  
  UPDATE p_city
SET p_city.City_Name = concat('Kabupaten', p_city.City_Name) 
WHERE P_CITY.City_Name IN (
select a.City_Id from (SELECT MAX(p_city.City_Id) AS maxid,City_Name FROM p_city JOIN p_city AS duplicates USING (City_Name) GROUP BY City_Name HAVING COUNT(*) > 1) a)